---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/instance: granite-chatbot

resources:
- deployment.yaml
- service.yaml
- route.yaml
- namespace.yaml
- configmap.yaml